# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import cnn_model_pb2 as cnn__model__pb2


class CnnModelStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ScoreCnnModel = channel.unary_unary(
        '/cnn_model.CnnModel/ScoreCnnModel',
        request_serializer=cnn__model__pb2.QueryRequest.SerializeToString,
        response_deserializer=cnn__model__pb2.QueryReply.FromString,
        )


class CnnModelServicer(object):

  def ScoreCnnModel(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CnnModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ScoreCnnModel': grpc.unary_unary_rpc_method_handler(
          servicer.ScoreCnnModel,
          request_deserializer=cnn__model__pb2.QueryRequest.FromString,
          response_serializer=cnn__model__pb2.QueryReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cnn_model.CnnModel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
