# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cnn_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cnn_model.proto',
  package='cnn_model',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63nn_model.proto\x12\tcnn_model\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\'\n\nQueryReply\x12\x0b\n\x03\x61pp\x18\x01 \x03(\t\x12\x0c\n\x04prob\x18\x02 \x03(\x02\x32M\n\x08\x43nnModel\x12\x41\n\rScoreCnnModel\x12\x17.cnn_model.QueryRequest\x1a\x15.cnn_model.QueryReply\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='cnn_model.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='cnn_model.QueryRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=59,
)


_QUERYREPLY = _descriptor.Descriptor(
  name='QueryReply',
  full_name='cnn_model.QueryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app', full_name='cnn_model.QueryReply.app', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='cnn_model.QueryReply.prob', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryReply'] = _QUERYREPLY

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'cnn_model_pb2'
  # @@protoc_insertion_point(class_scope:cnn_model.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)

QueryReply = _reflection.GeneratedProtocolMessageType('QueryReply', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREPLY,
  __module__ = 'cnn_model_pb2'
  # @@protoc_insertion_point(class_scope:cnn_model.QueryReply)
  ))
_sym_db.RegisterMessage(QueryReply)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class CnnModelStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ScoreCnnModel = channel.unary_unary(
          '/cnn_model.CnnModel/ScoreCnnModel',
          request_serializer=QueryRequest.SerializeToString,
          response_deserializer=QueryReply.FromString,
          )


  class CnnModelServicer(object):

    def ScoreCnnModel(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_CnnModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ScoreCnnModel': grpc.unary_unary_rpc_method_handler(
            servicer.ScoreCnnModel,
            request_deserializer=QueryRequest.FromString,
            response_serializer=QueryReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'cnn_model.CnnModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaCnnModelServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ScoreCnnModel(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaCnnModelStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ScoreCnnModel(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    ScoreCnnModel.future = None


  def beta_create_CnnModel_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('cnn_model.CnnModel', 'ScoreCnnModel'): QueryRequest.FromString,
    }
    response_serializers = {
      ('cnn_model.CnnModel', 'ScoreCnnModel'): QueryReply.SerializeToString,
    }
    method_implementations = {
      ('cnn_model.CnnModel', 'ScoreCnnModel'): face_utilities.unary_unary_inline(servicer.ScoreCnnModel),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_CnnModel_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('cnn_model.CnnModel', 'ScoreCnnModel'): QueryRequest.SerializeToString,
    }
    response_deserializers = {
      ('cnn_model.CnnModel', 'ScoreCnnModel'): QueryReply.FromString,
    }
    cardinalities = {
      'ScoreCnnModel': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'cnn_model.CnnModel', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
